# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.mattmoor.http.nodejs.functions"
version = "0.0.0"
name = "Node.js HTTP Function Buildpack"
homepage = "https://github.com/mattmoor/cloudevents-nodejs-fn"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"
